### ISSUE TITLE
Convert p4 quantities to floats 

### ISSUE THREAD

**Issue by harrypuuter** [KIT-CMS/ToBeNamedPrototype#18]
Hier muesst ihr aufpassen, das schreibt euch ein double raus und ihr habt am Ende evtl ein 2x so grosses ntuple ;) Selbes gilt auch fuer die anderen quantities unten.

```suggestion
        [](const ROOT::Math::PtEtaPhiMVector &p4) { return (float)p4.pt(); },
```

_Originally posted by @stwunsch in https://github.com/KIT-CMS/ToBeNamedPrototype/pull/17#discussion_r624116671_

**Comment by stwunsch** [comment]
If you write `Fixes #18` in the commit, then the related issues are getting closed automatically with merging the PR!

**Comment by harrypuuter** [comment]
ui nice :), i will try to remember
